/**
 * The vendored fudami-design bundle must stay honest.
 *
 * This site is static files served by Cloudflare Pages, so the package arrives as a
 * committed artifact rather than an npm install at request time. A committed copy of
 * someone else's build drifts silently - that is exactly how this repo's components.js and
 * shared.js forked from jisho's in the first place.
 *
 * The parity check skips when the sibling checkout is absent, because CI has one repo.
 */

const test = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const VENDORED = path.join(ROOT, 'vendor', 'fudami-design.browser.js');
const PACKAGE = path.join(ROOT, '..', 'fudami-design');

test('the bundle is present and marked generated', () => {
  const text = fs.readFileSync(VENDORED, 'utf8');
  assert.match(text.split('\n')[0], /GENERATED BY build\.js/);
  assert.match(text, /global\.FudamiDesign/);
});

test('every page loads the package before the files that call it', () => {
  for (const page of ['index.html', 'about.html', 'pricing.html', 'privacy.html', 'credits.html']) {
    const html = fs.readFileSync(path.join(ROOT, page), 'utf8');
    assert.ok(
      html.indexOf('vendor/fudami-design.browser.js') < html.indexOf('src="components.js"'),
      `${page} loads components.js before the package it calls`,
    );
  }
});

test('the site files build no markup from data', () => {
  for (const name of ['components.js', 'shared.js']) {
    const source = fs.readFileSync(path.join(ROOT, name), 'utf8');
    const offenders = source
      .split('\n')
      .filter((line) => /innerHTML\s*\+?=/.test(line) && !line.trim().startsWith('*') && !line.trim().startsWith('//'));
    assert.deepStrictEqual(offenders, [], `${name} assigns innerHTML`);
  }
});

test('the vendored copy matches a fresh package build', { skip: !fs.existsSync(path.join(PACKAGE, 'build.js')) }, () => {
  execFileSync('node', ['build.js'], { cwd: PACKAGE });
  assert.strictEqual(
    fs.readFileSync(VENDORED, 'utf8'),
    fs.readFileSync(path.join(PACKAGE, 'dist', 'chrome.browser.js'), 'utf8'),
    'vendor/fudami-design.browser.js is stale: (cd ../fudami-design && npm run build) then copy dist/chrome.browser.js here',
  );
});
